config/routes.rb
Rails.application.routes.draw do
  resources :microposts, only: %I[index destroy create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  def index
    @micropost = Micropost.new
    @microposts = Micropost.all.order("created_at desc")
  end

  # POST /microposts
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to microposts_url, notice: "Micropost was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url, notice: "Micropost was successfully destroyed." }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar bg-primary navbar-wrapper">
  <!-- Navbar content -->
  <div class="container-md">
    <a class="navbar-brand" href="#">Polkadot Cow</a>
    <button class="btn btn-primary navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-text" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-text">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "#", class: 'nav-link nav-home' do %>
            홈
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to "#", class: 'nav-link nav-notifications' do %>
            알림
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar_profile.html.erb
<div class="sidebar sidebar-profile">
  <div class="card" aria-hidden="true">
    <div class="card-body">
      <h5 class="card-title placeholder-glow">
        <span class="placeholder col-6"></span>
      </h5>
      <p class="card-text placeholder-glow">
        <span class="placeholder col-7"></span>
        <span class="placeholder col-4"></span>
        <span class="placeholder col-4"></span>
        <span class="placeholder col-6"></span>
        <span class="placeholder col-8"></span>
      </p>

      <p class="card-text placeholder-glow">
        <span class="placeholder col-4"></span>
        <span class="placeholder col-4"></span>
        <span class="placeholder col-6"></span>
        <span class="placeholder col-7"></span>
        <span class="placeholder col-8"></span>
      </p>

      <p class="card-text placeholder-glow">
        <span class="placeholder col-8"></span>
        <span class="placeholder col-4"></span>
        <span class="placeholder col-4"></span>
        <span class="placeholder col-6"></span>
        <span class="placeholder col-7"></span>
      </p>
    </div>
  </div>
</div>

app/views/layouts/_sidebar_trending.html.erb
<div class="sidebar sidebar-trending">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolkadotCow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="content-wrapper pt-4 d-flex justify-content-center">
      <div class="container-md row">
        <%= render "layouts/sidebar_profile" %>
        <div class="content">
          <%= yield %>
        </div>
        <%= render "layouts/sidebar_profile" %>
      </div>
    </div>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, class: "micropost-form") do |form| %>
  <div class="micropost-thumbnail">
    <%= image_tag "https://via.placeholder.com/40" %>
  </div>
  <div class="micropost-body">
    <%= form.text_area :content, placeholder: "무슨 일이 일어나고 있나요?", class: 'form-control' %>
    <%= form.hidden_field :username, value: "아무개" %>

    <div class="d-flex justify-content-end my-2 mb-4">
      <%= form.submit "글쓰기", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div id="<%= dom_id micropost %>" class="micropost-list-entry p-2">
  <div class="micropost-thumbnail">
    <%= image_tag "https://via.placeholder.com/40" %>
  </div>
  <div class="micropost-body">
    <div class="micropost-header d-flex justify-content-between mb-1">
      <div class="micropost-information">
        <b><%= micropost.username %></b>
      </div>
      <button type="button" class="btn dropdown-toggle micropost-action" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-three-dots"></i>
      </button>
      <ul class="dropdown-menu dropdown-menu-end">
        <%#= link_to 메서드로는 해결되지 않아 button_to로 대체함 %>
        <li class="dropdown-item">
          <%= button_to "글 삭제하기", micropost_path(micropost), method: :delete %>
        </li>
      </ul>
    </div>
    <div class="micropost-content">
      <%= micropost.content %>
    </div>
  </div>
</div>

app/views/microposts/index.html.erb
<p style="color: green"><%= notice %></p>

<%= render "form", micropost: @micropost %>

<div id="microposts" class="card">
  <% @microposts.each do |micropost| %>
    <div class="border-bottom">
      <%= render micropost %>
    </div>
  <% end %>
</div>